{
  "build": "py311hca03da5_0",
  "build_number": 0,
  "channel": "https://repo.anaconda.com/pkgs/main/osx-arm64",
  "constrains": [],
  "depends": [
    "cryptography >=3.4.0",
    "keyring",
    "pkce",
    "pydantic",
    "pyjwt",
    "python >=3.11,<3.12.0a0",
    "python-dotenv",
    "requests",
    "semver <3"
  ],
  "extracted_package_dir": "/Users/Peizhi/anaconda3/pkgs/anaconda-cloud-auth-0.4.1-py311hca03da5_0",
  "files": [
    "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/INSTALLER",
    "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/METADATA",
    "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/RECORD",
    "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/REQUESTED",
    "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/WHEEL",
    "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/direct_url.json",
    "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/entry_points.txt",
    "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/licenses/LICENSE",
    "lib/python3.11/site-packages/anaconda_cloud_auth/__init__.py",
    "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/__init__.cpython-311.pyc",
    "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/_version.cpython-311.pyc",
    "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/actions.cpython-311.pyc",
    "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/cli.cpython-311.pyc",
    "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/client.cpython-311.pyc",
    "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/config.cpython-311.pyc",
    "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/console.cpython-311.pyc",
    "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/exceptions.cpython-311.pyc",
    "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/handlers.cpython-311.pyc",
    "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/jwt.cpython-311.pyc",
    "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/panel.cpython-311.pyc",
    "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/token.cpython-311.pyc",
    "lib/python3.11/site-packages/anaconda_cloud_auth/_version.py",
    "lib/python3.11/site-packages/anaconda_cloud_auth/actions.py",
    "lib/python3.11/site-packages/anaconda_cloud_auth/cli.py",
    "lib/python3.11/site-packages/anaconda_cloud_auth/client.py",
    "lib/python3.11/site-packages/anaconda_cloud_auth/config.py",
    "lib/python3.11/site-packages/anaconda_cloud_auth/console.py",
    "lib/python3.11/site-packages/anaconda_cloud_auth/exceptions.py",
    "lib/python3.11/site-packages/anaconda_cloud_auth/handlers.py",
    "lib/python3.11/site-packages/anaconda_cloud_auth/jwt.py",
    "lib/python3.11/site-packages/anaconda_cloud_auth/panel.py",
    "lib/python3.11/site-packages/anaconda_cloud_auth/py.typed",
    "lib/python3.11/site-packages/anaconda_cloud_auth/token.py"
  ],
  "fn": "anaconda-cloud-auth-0.4.1-py311hca03da5_0.conda",
  "legacy_bz2_md5": "ae342a5f45b80c4d64fedbf44b8ddd51",
  "legacy_bz2_size": 44011,
  "license": "BSD-3-Clause",
  "license_family": "BSD",
  "link": {
    "source": "/Users/Peizhi/anaconda3/pkgs/anaconda-cloud-auth-0.4.1-py311hca03da5_0",
    "type": 1
  },
  "md5": "989aa75a0a822f504817259c15d17510",
  "name": "anaconda-cloud-auth",
  "package_tarball_full_path": "/Users/Peizhi/anaconda3/pkgs/anaconda-cloud-auth-0.4.1-py311hca03da5_0.conda",
  "paths_data": {
    "paths": [
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/INSTALLER",
        "path_type": "hardlink",
        "sha256": "d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8",
        "sha256_in_prefix": "d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8",
        "size_in_bytes": 5
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/METADATA",
        "path_type": "hardlink",
        "sha256": "5c835695f0b8e4dda9cda67193ca34e306d2ea905928efc93b29b1daa00573f1",
        "sha256_in_prefix": "5c835695f0b8e4dda9cda67193ca34e306d2ea905928efc93b29b1daa00573f1",
        "size_in_bytes": 8268
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/RECORD",
        "path_type": "hardlink",
        "sha256": "1e7cbacae0fc14e9107bc20ebd1d9c6d2023882aa2e019777c86271e04757ef1",
        "sha256_in_prefix": "1e7cbacae0fc14e9107bc20ebd1d9c6d2023882aa2e019777c86271e04757ef1",
        "size_in_bytes": 2597
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/REQUESTED",
        "path_type": "hardlink",
        "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "sha256_in_prefix": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "size_in_bytes": 0
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/WHEEL",
        "path_type": "hardlink",
        "sha256": "4c93e729db6b4ae7bbc59fc0546929f585dcbc3ae86ec8c176cd5dbb7371e9d7",
        "sha256_in_prefix": "4c93e729db6b4ae7bbc59fc0546929f585dcbc3ae86ec8c176cd5dbb7371e9d7",
        "size_in_bytes": 87
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/direct_url.json",
        "path_type": "hardlink",
        "sha256": "57fcabc3584fc37443981312dfdcbdd024fad8ffaa96879dd3b536b3b26f49ec",
        "sha256_in_prefix": "57fcabc3584fc37443981312dfdcbdd024fad8ffaa96879dd3b536b3b26f49ec",
        "size_in_bytes": 150
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/entry_points.txt",
        "path_type": "hardlink",
        "sha256": "edf9f68dbbb2afd3f30795d7df4891ec8183d17dc4bd5731d48672c8bb7097aa",
        "sha256_in_prefix": "edf9f68dbbb2afd3f30795d7df4891ec8183d17dc4bd5731d48672c8bb7097aa",
        "size_in_bytes": 82
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth-0.4.1.dist-info/licenses/LICENSE",
        "path_type": "hardlink",
        "sha256": "8372f6c92cbeb44c769041fd46cdaf12946c48743ed714c29059b0d917626cb8",
        "sha256_in_prefix": "8372f6c92cbeb44c769041fd46cdaf12946c48743ed714c29059b0d917626cb8",
        "size_in_bytes": 1544
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/__init__.py",
        "path_type": "hardlink",
        "sha256": "cc28c86f9eb98fc5605de1af80e36af7c4b8685e97349374a63c9d55200135cf",
        "sha256_in_prefix": "cc28c86f9eb98fc5605de1af80e36af7c4b8685e97349374a63c9d55200135cf",
        "size_in_bytes": 394
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/__init__.cpython-311.pyc",
        "path_type": "hardlink",
        "sha256": "12e44781f0221209adcaa7d78a11a9da285367d2c020e0362dff9cd481d998ff",
        "sha256_in_prefix": "12e44781f0221209adcaa7d78a11a9da285367d2c020e0362dff9cd481d998ff",
        "size_in_bytes": 613
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/_version.cpython-311.pyc",
        "path_type": "hardlink",
        "sha256": "fd7a43427b4c84ce7f0da3c7e39057e1c485c70536df89d95498075f6fe411b5",
        "sha256_in_prefix": "fd7a43427b4c84ce7f0da3c7e39057e1c485c70536df89d95498075f6fe411b5",
        "size_in_bytes": 627
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/actions.cpython-311.pyc",
        "path_type": "hardlink",
        "sha256": "792f8633f9371e9c0e05b59232250784dfaa9656f0a2b0c3ab194341b2d3cbfa",
        "sha256_in_prefix": "792f8633f9371e9c0e05b59232250784dfaa9656f0a2b0c3ab194341b2d3cbfa",
        "size_in_bytes": 12722
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/cli.cpython-311.pyc",
        "path_type": "hardlink",
        "sha256": "7d0c10a5855203c33aae11f0598b8f1d00e8d3470fb947af097d16bb2c6e4c34",
        "sha256_in_prefix": "7d0c10a5855203c33aae11f0598b8f1d00e8d3470fb947af097d16bb2c6e4c34",
        "size_in_bytes": 1110
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/client.cpython-311.pyc",
        "path_type": "hardlink",
        "sha256": "13286b32fdc355d02565ee59d2911d7a8e29121f6d292d18897e522c545f3f37",
        "sha256_in_prefix": "13286b32fdc355d02565ee59d2911d7a8e29121f6d292d18897e522c545f3f37",
        "size_in_bytes": 11506
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/config.cpython-311.pyc",
        "path_type": "hardlink",
        "sha256": "64e683eae7321c7f02a5dbfc9c5de84b6347d3d542b137842ed0bec7397b0042",
        "sha256_in_prefix": "64e683eae7321c7f02a5dbfc9c5de84b6347d3d542b137842ed0bec7397b0042",
        "size_in_bytes": 4642
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/console.cpython-311.pyc",
        "path_type": "hardlink",
        "sha256": "aeda602d22175a6f57233497f7a54a3af03ff95296395c6717a7fccd481985a9",
        "sha256_in_prefix": "aeda602d22175a6f57233497f7a54a3af03ff95296395c6717a7fccd481985a9",
        "size_in_bytes": 2247
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/exceptions.cpython-311.pyc",
        "path_type": "hardlink",
        "sha256": "b914b77e4daf5c4477de7edc983483ed7758b7c579d7d3df3c83b67fe8319734",
        "sha256_in_prefix": "b914b77e4daf5c4477de7edc983483ed7758b7c579d7d3df3c83b67fe8319734",
        "size_in_bytes": 1162
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/handlers.cpython-311.pyc",
        "path_type": "hardlink",
        "sha256": "609adb2a4e9dad8b1ef2fc2f465775aa05fb027f61325eeb352fc7dd823a0251",
        "sha256_in_prefix": "609adb2a4e9dad8b1ef2fc2f465775aa05fb027f61325eeb352fc7dd823a0251",
        "size_in_bytes": 9029
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/jwt.cpython-311.pyc",
        "path_type": "hardlink",
        "sha256": "131067274616b75c3e1b5ebbd9fdb322680c899a65a3d55fe0f6ebd007960b71",
        "sha256_in_prefix": "131067274616b75c3e1b5ebbd9fdb322680c899a65a3d55fe0f6ebd007960b71",
        "size_in_bytes": 2010
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/panel.cpython-311.pyc",
        "path_type": "hardlink",
        "sha256": "06fbad81a8e11dbb228629a80e3c13b64b186c8eec91d7433e68b9407bcb4d0f",
        "sha256_in_prefix": "06fbad81a8e11dbb228629a80e3c13b64b186c8eec91d7433e68b9407bcb4d0f",
        "size_in_bytes": 2950
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/__pycache__/token.cpython-311.pyc",
        "path_type": "hardlink",
        "sha256": "0a7ef05584df400189d4105f6a027586f3cf6b38577676ae46a567d86214a1c9",
        "sha256_in_prefix": "0a7ef05584df400189d4105f6a027586f3cf6b38577676ae46a567d86214a1c9",
        "size_in_bytes": 13970
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/_version.py",
        "path_type": "hardlink",
        "sha256": "1fac40737ddb27098ed28614f8eeffc162279860227cd1a2e823ba9214f41b58",
        "sha256_in_prefix": "1fac40737ddb27098ed28614f8eeffc162279860227cd1a2e823ba9214f41b58",
        "size_in_bytes": 411
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/actions.py",
        "path_type": "hardlink",
        "sha256": "0f469060df382a8e1d6b04b613083640e8f95f05fe90f451ac7235aef9ac2b1d",
        "sha256_in_prefix": "0f469060df382a8e1d6b04b613083640e8f95f05fe90f451ac7235aef9ac2b1d",
        "size_in_bytes": 9628
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/cli.py",
        "path_type": "hardlink",
        "sha256": "f27091925ba9a0a4c4d8ecf6670ef16177a56cd492bd7720dd25c411f0703c8b",
        "sha256_in_prefix": "f27091925ba9a0a4c4d8ecf6670ef16177a56cd492bd7720dd25c411f0703c8b",
        "size_in_bytes": 458
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/client.py",
        "path_type": "hardlink",
        "sha256": "707a1b91782cbbdb29486b27e4693e4ed5bfb563ce51a5c65f7dc38f9591234b",
        "sha256_in_prefix": "707a1b91782cbbdb29486b27e4693e4ed5bfb563ce51a5c65f7dc38f9591234b",
        "size_in_bytes": 7739
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/config.py",
        "path_type": "hardlink",
        "sha256": "08d8a6a04fb6d35fb7aed1890702ee460522c83e9a7019f9681fa841f9a8ce58",
        "sha256_in_prefix": "08d8a6a04fb6d35fb7aed1890702ee460522c83e9a7019f9681fa841f9a8ce58",
        "size_in_bytes": 2575
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/console.py",
        "path_type": "hardlink",
        "sha256": "5fb293ce7ee613ac1699216ec8852e51ab9cef333826de1803943e750d19ceb4",
        "sha256_in_prefix": "5fb293ce7ee613ac1699216ec8852e51ab9cef333826de1803943e750d19ceb4",
        "size_in_bytes": 868
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/exceptions.py",
        "path_type": "hardlink",
        "sha256": "e054b868d94d4cf3cb437e463dff1a8b41fb5e2573a174fa54ecf9a9f09f33e9",
        "sha256_in_prefix": "e054b868d94d4cf3cb437e463dff1a8b41fb5e2573a174fa54ecf9a9f09f33e9",
        "size_in_bytes": 247
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/handlers.py",
        "path_type": "hardlink",
        "sha256": "756b0f0cd2f44ad8efd249086ab9b53826aa9dde72adbcf7d181fa5b4d590a77",
        "sha256_in_prefix": "756b0f0cd2f44ad8efd249086ab9b53826aa9dde72adbcf7d181fa5b4d590a77",
        "size_in_bytes": 5125
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/jwt.py",
        "path_type": "hardlink",
        "sha256": "8e7400efb013e37c2c6be304147d1585ed81c3975270eef4e9c697faefda41de",
        "sha256_in_prefix": "8e7400efb013e37c2c6be304147d1585ed81c3975270eef4e9c697faefda41de",
        "size_in_bytes": 1099
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/panel.py",
        "path_type": "hardlink",
        "sha256": "1f46f93a78b6fed2267b6677c71b14242fc8fd270fa61782c35bec1bff4d9f61",
        "sha256_in_prefix": "1f46f93a78b6fed2267b6677c71b14242fc8fd270fa61782c35bec1bff4d9f61",
        "size_in_bytes": 1598
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/py.typed",
        "path_type": "hardlink",
        "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "sha256_in_prefix": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "size_in_bytes": 0
      },
      {
        "_path": "lib/python3.11/site-packages/anaconda_cloud_auth/token.py",
        "path_type": "hardlink",
        "sha256": "da8739a32e58ecaa9fa684c6939116a01e52248e4dd6efed34a77b28b0d51583",
        "sha256_in_prefix": "da8739a32e58ecaa9fa684c6939116a01e52248e4dd6efed34a77b28b0d51583",
        "size_in_bytes": 8237
      }
    ],
    "paths_version": 1
  },
  "requested_spec": "None",
  "sha256": "383e7667edba730c0aaf08fb9efb39cdd1e9c61903e99b481321acbcc0bbc470",
  "size": 46231,
  "subdir": "osx-arm64",
  "timestamp": 1710260208514,
  "url": "https://repo.anaconda.com/pkgs/main/osx-arm64/anaconda-cloud-auth-0.4.1-py311hca03da5_0.conda",
  "version": "0.4.1"
}